# Generated by Django 4.2.10 on 2024-03-02 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_str', models.CharField(max_length=200)),
                ('desc_str', models.CharField(max_length=750)),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('unit', models.CharField(max_length=30)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_viewer.material')),
            ],
        ),
    ]
