# Generated by Django 4.2.10 on 2024-03-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cost_per_unit',
            field=models.FloatField(default=0.0, verbose_name='Cost Per Unit'),
        ),
        migrations.AddField(
            model_name='material',
            name='cost_unit',
            field=models.CharField(choices=[('kgs', 'Kgs'), ('lbs', 'Lbs'), ('g', 'G'), ('oz', 'Oz'), ('floz', 'Floz'), ('tbsp', 'Tbsp'), ('tsp', 'Tsp'), ('gal', 'Gal')], default='g', max_length=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='cost',
            field=models.FloatField(default=0, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='material',
            name='desc_str',
            field=models.CharField(blank=True, max_length=750, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name_str',
            field=models.CharField(max_length=200, verbose_name='Material Name'),
        ),
    ]
