# Generated by Django 4.2.10 on 2024-03-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_viewer', '0002_material_cost_per_unit_material_cost_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cost_unit_amount',
            field=models.FloatField(default=1.0, verbose_name='Costing Amount'),
        ),
    ]
