# Generated by Django 4.2.10 on 2024-03-13 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_viewer', '0003_material_cost_unit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('kgs', 'Kgs'), ('lbs', 'Lbs'), ('g', 'G'), ('oz', 'Oz'), ('floz', 'Floz'), ('tbsp', 'Tbsp'), ('tsp', 'Tsp'), ('gal', 'Gal')], default='g', max_length=10),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_str', models.CharField(max_length=200, verbose_name='Material Name')),
                ('desc_str', models.CharField(blank=True, max_length=750, verbose_name='Description')),
                ('ingredients', models.ManyToManyField(through='recipe_viewer.Ingredient', to='recipe_viewer.material')),
            ],
        ),
        migrations.CreateModel(
            name='ProceduralStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_desc', models.CharField(blank=True, max_length=1500, verbose_name='Description')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_viewer.recipe')),
                ('step_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe_viewer.material')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe_viewer.recipe'),
        ),
    ]
