# Generated by Django 4.2.10 on 2024-03-13 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_viewer', '0004_alter_ingredient_unit_recipe_proceduralstep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_viewer.recipe'),
        ),
    ]
